
// Stripe Price IDs (Auto-generated by seed script)

// Monthly Subscriptions (Synced to membership_types table)
export const STRIPE_PRICES = {
    SUBSCRIPTIONS: {
        M2_60: 'price_1SsZbBP0UQGtpYXmqRQpFexd',
        M4_60: 'price_1SsZbCP0UQGtpYXm4OQmrzC7',
        M2_90: 'price_1SsZbEP0UQGtpYXm1FkQkR8h',
        M4_90: 'price_1SsZbFP0UQGtpYXmCsHxCGnR',
    },
    TICKETS: {
        // Ticket-M2-60: Additional lesson for M2-60 member
        M2_60: 'price_1SsZbGP0UQGtpYXmVR2b4iEg',
        // Ticket-M4-60: Additional lesson for M4-60 member
        M4_60: 'price_1SsZbHP0UQGtpYXmumDpzB07',
        // Ticket-M2-90: Additional lesson for M2-90 member
        M2_90: 'price_1SsZbIP0UQGtpYXmfqdLvghI',
        // Ticket-M4-90: Additional lesson for M4-90 member
        M4_90: 'price_1SsZbJP0UQGtpYXm3SVUighI',

        // Visitor / Standard One-time
        VISITOR_60: 'price_1SsZbKP0UQGtpYXmPjuw7uhi',
        VISITOR_90: 'price_1SsZbLP0UQGtpYXmJBUEWEP2',
    },
} as const;

// Helper to get ticket price ID based on membership name
export const getTicketPriceIdFromMembershipName = (membershipName: string | null, duration: number) => {
    // membershipName expected: '月2回（60分）', '月4回（90分）' etc.

    if (!membershipName) {
        return duration === 90 ? STRIPE_PRICES.TICKETS.VISITOR_90 : STRIPE_PRICES.TICKETS.VISITOR_60;
    }

    // Map DB Name to Key
    // Simple logic: Check inclusion
    let key = '';
    if (membershipName.includes('月2回') && membershipName.includes('60分')) key = 'M2_60';
    else if (membershipName.includes('月4回') && membershipName.includes('60分')) key = 'M4_60';
    else if (membershipName.includes('月2回') && membershipName.includes('90分')) key = 'M2_90';
    else if (membershipName.includes('月4回') && membershipName.includes('90分')) key = 'M4_90';
    else {
        // Unknown membership or visitor
        return duration === 90 ? STRIPE_PRICES.TICKETS.VISITOR_90 : STRIPE_PRICES.TICKETS.VISITOR_60;
    }

    // @ts-ignore
    const priceId = STRIPE_PRICES.TICKETS[key];
    return priceId || (duration === 90 ? STRIPE_PRICES.TICKETS.VISITOR_90 : STRIPE_PRICES.TICKETS.VISITOR_60);
};
