-- leadsテーブルを体験フォームの全項目に対応させる
ALTER TABLE leads 
ADD COLUMN IF NOT EXISTS full_name_kana TEXT,
ADD COLUMN IF NOT EXISTS birth_date DATE,
ADD COLUMN IF NOT EXISTS second_student_name TEXT,
ADD COLUMN IF NOT EXISTS second_student_kana TEXT,
ADD COLUMN IF NOT EXISTS second_student_birth_date DATE,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS datetime1 TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS datetime2 TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS datetime3 TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS frequency TEXT,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS skill_level TEXT;
